### ISSUE TITLE
Real time chat

### ISSUE THREAD

**Issue by sofhin** [munafio/chatify#102]
![Capture](https://user-images.githubusercontent.com/67450858/119293308-bb5be980-bc84-11eb-912d-33032b5000f0.PNG)

What's wrong with it?
I can get the notification, but I have to click on the user to update the message.
I do enable the client events in the pusher.

Any idea on how to solve it?

This is what I got in the debugger
![image](https://user-images.githubusercontent.com/67450858/119293403-f100d280-bc84-11eb-91e4-bc9593c22093.png)

**Comment by munafio** [comment]
@sofhin 
I have reviewed your issue, and I'll check it on my side because it supposed to be work unless you have changed something causing this issue.

- Is there any errors that may prevent this action!? 
- Have you done any changes in the code? 
- When you first installed the package, was it working as expected?

Please provide me with your answers to help fixing this issue.

**Comment by sofhin** [comment]
There is no error as shown in the second screenshot, that's why I am curious as well.
Yes, I added two functions for deleting the selected message.
Yes, it works well. Even I copy and paste the whole code.js from your repository to my current one, it still the same.

**Comment by munafio** [comment]
> There is no error as shown in the second screenshot, that's why I am curious as well.
> 
> Yes, I added two functions for deleting the selected message.
> 
> Yes, it works well. Even I copy and paste the whole code.js from your repository to my current one, it still the same.

Since it was working well! So you have to track what you have done from changes to know where the issue is.

**Comment by sofhin** [comment]
well, I think that's the only solution
