### ISSUE TITLE
Page at endpoint /chatify need to be refreshed before showing history

### ISSUE THREAD

**Issue by 24Degrees** [munafio/chatify#144]
Hi Munafio,

while testing I discovered that I always need to refresh the page whenever I visit the 127.0.0.1/chatify url. It shows no history at first but when I do a reload, then it's ok.

However, if I change the link (not the route) to http://127.0.0.1:8000/chatify# with an hashtag, it all seems to be working fine.

Thanks for the nice work.

kind regards,

Michael

**Comment by munafio** [comment]
@24Degrees Hi, 
What do you mean by shows no history? can you provide me more details?

Thank you.

**Comment by 24Degrees** [comment]
Hi Munafio, 

The GIF below shows what's happening. Of course it can always be some mistake we made, but this is the result:

![2021-09-26 13 30 42](https://user-images.githubusercontent.com/17310214/134805893-a9eab882-63e0-40e4-a8e2-a6844190eeef.gif)

**Comment by munafio** [comment]
@24Degrees I think this issue is related to your browser! can you check it on other browsers as well?

**Comment by 24Degrees** [comment]
This is the Chrome version. Same problem. I already checked Firefox too but it still might be a problem of Mac osX or redirecting or so...

![2021-09-26 13 39 02](https://user-images.githubusercontent.com/17310214/134806120-404d1a74-0ef3-4551-a6e1-2ffce541a2e1.gif)

**Comment by 24Degrees** [comment]
Test repo is here: https://github.com/24Degrees/Chatify-from-Vemto

**Comment by munafio** [comment]
@24Degrees I have installed your demo app and worked on it on my local development server, and I came up with the reason behind this issue, because you are using Livewire navigation which is navigate between the routes using Ajax request! and for some reason it is not working with Ajax! thats why you need to reload the page to get it working.

I'll figure it out and fix this issue if its related to Chatify. until that, you can fix this issue using a `target` attribute on the link that navigates you to Chatify as the following at `nav.blade.php` :
```
<a class="dropdown-item" href="{{ route('chatify') }}" target="_new">
         {{ __('Chatify') }}
 </a>
```
This will open the route in a new tab which is (reloading the page) and it will work as expected.

Thank you.

**Comment by munafio** [comment]
@24Degrees I have installed your demo app and worked on it on my local development server, and I came up with the reason behind this issue, because you are using Livewire navigation which is navigate between the routes using Ajax request!

Chatify is not designed with Livewire and won't work with it, it is separated and uses only jQuery. When you navigate to `/chatify` with Livewire its uses Ajax behind the scenes to load Chatify and in this case Chatify will considered as one of your blade views that uses Livewire, so when you reload the page then it will uses only Chatify scripts without Livewire.

You can have a quick fix for this issue using a `target` attribute on the link that navigates you to Chatify as the following at `nav.blade.php` :
```
<a class="dropdown-item" href="{{ route('chatify') }}" target="_new">
         {{ __('Chatify') }}
 </a>
```
This will open the route in a new tab which is (reloading the page) and it will work as expected.

Thank you.
