### ISSUE TITLE
The user chat is not showing

### ISSUE THREAD

**Issue by ArwaElballali** [munafio/chatify#158]
When I click on the user i want to chat with the URL changes to that user id but the chat is not opening, and i installed in perfectly fine, I'm using Laravel 8.

**Comment by munafio** [comment]
@ArwaElballali hi, please provide more info about your issue and mention Chatify version you are using.

As Chatify v1.3.x it is automatically changes the url according to the user you are chatting with.

**Comment by hasanalihaolader** [comment]
when using  ^v1.3 `getContacts() `is call post method but web.php and api.php write get method
as you see 
![Screenshot from 2022-01-08 23-49-49](https://user-images.githubusercontent.com/23256533/148654357-ea0da6b1-0384-4541-8f70-9b8d48c07f2f.png)
but `getContacts() ` is working fine as well as older version v1.2 because web.php is calling getContacts as post method

**Comment by getupzee** [comment]
I am getting the same issue. 

what is solution to it

![image](https://user-images.githubusercontent.com/3645143/168967136-1119d44a-2d82-4e80-8dd5-7ef4614e3416.png)

**Comment by munafio** [comment]
> I am getting the same issue. 
> 
> 
> 
> what is solution to it
> 
> 
> 
> ![image](https://user-images.githubusercontent.com/3645143/168967136-1119d44a-2d82-4e80-8dd5-7ef4614e3416.png)
> 
> 

This issue is mysql related issue with 'group_by' .. in order to solve this issue, go to config/database.php the from (mysql) make the (strict mode) disabled.

**Comment by munafio** [comment]
@hasan689009 @getupzee please keep the comments here related to the issue itself.. if you are facing another (different) issue, then open a new issue.
