### ISSUE TITLE
"Attempt to read property id " this is the error when I click to show Conversation

### ISSUE THREAD

**Issue by ellwo** [munafio/chatify#162]
Attempt to read property "id" on null', exception: 'ErrorException'
, file: \\chatify-demo-master\\vendor\\munafio\\chatify\\src\\ChatifyMessenger.php', line: 115, trace: Array(50)}
responseText: "{\n    \"message\": \"Attempt to read property \\\"id\\\" on null\",\n    \"exception\": \"ErrorException\",\n

**Comment by Zafeer999** [comment]
i am also facing the same issue with api

**Comment by munafio** [comment]
@Zafeer999 @ellwo Can you please provide more info about your issue?

**Comment by jonoti4658** [comment]
I am also facing same issue with API, can you explain a bit more.

**Comment by sharingankakashi** [comment]
Hello,
Trying to access chat apis.Im not able to get data from **Auth::user()** .Insted of **Auth::** I used **auth('sanctum')** its worked for me.Is there any other way because modifying vendors files its not good.

Auth API
http://127.0.0.1:8000/chatify/api/chat/auth


ERROR
"message": "Attempt to read property \"id\" on null",
    "exception": "ErrorException",
    "file": "C:\\xampp\\htdocs\\chatify\\vendor\\munafio\\chatify\\src\\Http\\Controllers\\Api\\MessagesController.php",
    "line": 31,


Thanks.

**Comment by sharingankakashi** [comment]
after publishing controllers I changed all **Auth::** to **auth('sanctum')**

https://chatify.munafio.com/customizations

php artisan vendor:publish --tag=chatify-controllers


Its worked for me.
