### ISSUE TITLE
Sensitive hidden fields are visible in api response

### ISSUE THREAD

**Issue by gtu-myowin** [munafio/chatify#196]
I have define following fields hidden in my User model.

```php
protected $hidden = [
	// 'email',
	'password',
	'remember_token',
	'two_factor_recovery_codes',
	'two_factor_secret',
];
```

But they are still visible in api response as you can see in screenshot

![Screen-Shot-2022-07-10-at-12-48-25-PM-png-1606×1642-](https://user-images.githubusercontent.com/2696343/178133940-ae9c1cda-1de2-4968-b4ae-708136ff48c9.png)

I don't think it is good for security to make them visible. Please let me know how can I hide them in response.

**Comment by munafio** [comment]
@gtu-myowin since we are using raw sql queries, then we'll get all the columns from the database (users table).

Laravel docs:
> Hiding Attributes From Array Or JSON Conversion
> Sometimes you may wish to limit the attributes that are included in your model's array or JSON form, such as passwords. To do so, add a hidden property definition to your model.

Also read this about [model serialization](https://laravel.com/docs/9.x/eloquent-serialization).

**Solution**: you can either select the columns you want one by one using sql queries, or use [Laravel resources](https://laravel.com/docs/9.x/eloquent-resources#main-content) to achieve this which I recommend.

So, it depends on you.

**Comment by XFAISAL** [comment]
Im facing the same issue

**Comment by gtu-myowin** [comment]
@XFAISAL munafio already given 2 solutions.
