### ISSUE TITLE
API request /getContacts fails

### ISSUE THREAD

**Issue by floreapaun** [munafio/chatify#220]
When I go localhost/chatify API request fails:

![Screenshot 2022-10-19 144038](https://user-images.githubusercontent.com/1117393/196681161-2ceeb914-be9b-42bb-bd55-3759e4583759.png)

Response message:
``
SQLSTATE[42000]: Syntax error or access violation: 1055 'chat.users.name' isn't in GROUP BY (SQL: select count(*) as aggregate from (select `users`.*, MAX(ch_messages.created_at) max_created_at from `ch_messages` inner join `users` on `ch_messages`.`from_id` = `users`.`id` or `ch_messages`.`to_id` = `users`.`id` where (`ch_messages`.`from_id` = 1 or `ch_messages`.`to_id` = 1) and `users`.`id` != 1 group by `users`.`id`) as `aggregate_table`)
``

**Comment by NawrasBukhari** [comment]
head to config/database.php and make strict false.

**Comment by floreapaun** [comment]
The guy [in here](https://sinnbeck.dev/posts/laravel-groupby-error) says it can be unpredictable and lead to problems down the road.

**Comment by munafio** [comment]
@floreapaun This issue is duplicated, you can follow this solution ([issue 1](https://github.com/munafio/chatify/issues/205#issuecomment-1219399270)) or if you have a better implementation you can write your own, Chatify is [fully customizable](https://chatify.munafio.com/customizations) .. then also you can open a PR.

Thank you
