### ISSUE TITLE
Group feature ?

### ISSUE THREAD

**Issue by dgillier** [munafio/chatify#221]
Hi,
This is a really great component !

Any idea if a group feature is planned, if yes when ?

Thanks, Denis

**Comment by munafio** [comment]
@dgillier Hi,👋🏻
Currently not planned to work on this feature .. It was planned to be released with Chatify v2, but because of the time and effort I'm spending on this project without any support, I stopped the plan just for now.
I will write an announcement very soon about the plan and this project, so stay tuned until then.

Have a good day.
