### ISSUE TITLE
Delete Message by id problem

### ISSUE THREAD

**Issue by ManarangID** [munafio/chatify#238]
I has try to delete message by id, but the modal alert doesn't disappear when use clientChannel variable in code.js.
![messenger](https://user-images.githubusercontent.com/119088585/213360286-2e7b77e2-551a-402c-b1f8-3b24258b8b07.png)

**Comment by munafio** [comment]
@ManarangID Sorry, My bad! 
this because we do not have `clientChannel` variable, instead we have `clientSendChannel` and `clientListenChannel` variables.. 

I will fix this issue very soon .. for now, you can fix it by making changes on `code.js` on the delete action we need `clientSendChannel` instead of `clientChannel`

**Comment by ManarangID** [comment]
> @ManarangID Sorry, My bad! this because we do not have `clientChannel` variable, instead we have `clientSendChannel` and `clientListenChannel` variables..
> 
> I will fix this issue very soon .. for now, you can fix it by making changes on `code.js` on the delete action we need `clientSendChannel` instead of `clientChannel`

thanks its work for now

**Comment by munafio** [comment]
new fix release now out for this issue. v1.5.5

**Comment by ManarangID** [comment]
> new fix release now out for this issue. v1.5.5

thanks
