### ISSUE TITLE
Installation for for Laravel over Nuxt.js

### ISSUE THREAD

**Issue by connecteev** [munafio/chatify#27]
I took a look at the functionality in the YouTube demo video, looks nicely done. 

My tech stack is Laravel (back end) talking to a Nuxt.js front-end.  What are the steps needed to install this on Nuxt + Laravel? Would chatify work with that?

**Comment by munafio** [comment]
Chatify v1.0 does not support integration with (react, vue, angular,nextjs, nuxtjs ...etc) or any other front-end frameworks! because it does not provide API's for that!!

But..!
In the next release (v2.0) it will be re-developed completely with Vue.js .. so it will provide you Back-End API's so that you can easily integrate it with the any front-end framework or even for mobile development.

**Comment by connecteev** [comment]
@munafio thanks for the update, any idea when the APIs and a vue version would become available?
