### ISSUE TITLE
Socket.Io

### ISSUE THREAD

**Issue by cypriotxx** [munafio/chatify#52]
Do you have any plans to release Socket.IO version of this pls without pusher ?

**Comment by munafio** [comment]
Maybe with v2 will have (socket.io, laravel websokets, and pusher) support

**Comment by platomedical** [comment]
Awesome project @munafio. Perhaps using the native Broadcasting (https://laravel.com/docs/8.x/broadcasting) would be more extendable?

**Comment by munafio** [comment]
@platomedical Thanks for reaching out.
Yes, As I announced before, Chatify v2 completely will be re-designed.

**Comment by bruceleedrupal** [comment]
When would version 2 released？

**Comment by rassemdev** [comment]
@munafio  Any update on that?

**Comment by munafio** [comment]
@munafio Actually, no. Still not worked on the v2 because of my own responsibilities and my work, also because I did not get a support from anyone to keep working on it .. but I will work on it ASAP. And Still releasing updates on the current version.
At the mean time, you can make it your self because with Chatify you can customize/add anything you want. Read the docs: chatify.munafio.com
